# Generated by Django 5.0.6 on 2024-07-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videourl', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Url',
            new_name='PlaylistUrl',
        ),
        migrations.RenameField(
            model_name='playlisturl',
            old_name='url',
            new_name='playlisturl',
        ),
    ]
